services:
  ai:
    build: ./AI
    expose: 
      - "7555"
  db:
    build: ./db
    expose: 
      - "7788"
  app:
    build: ./app
    ports: 
      - "5555:5000"
    links: 
      - "db"
      - "ai"
