services:
  ai:
    build: ./AI
    ports:
      - "7555:5000"
  db:
    build: ./db
    ports:
      - "7788:5000"
  app:
    build: ./app
    ports: 
      - "5555:5000"
    links: 
      - "db"
      - "ai"
